In [1]:
import pandas as pd

In [2]:
csv = pd.read_csv("../combined_management.csv",keep_default_na=True,na_values=["None", "none", "NaN", "-"],low_memory=False,dtype={"company_id": str})
csv["company_id"] = csv["company_id"].astype(str)
csv.head()

,company_id,company_url,Name,Designation,Role,Since
0,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
1,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
2,5238,https://my.bursamalaysia.com/stock-details?sto...,Mr. Benyamin Bin Ismail,Chief Executive Officer,Officer,NaN
3,5238,https://my.bursamalaysia.com/stock-details?sto...,Ms. Lavinia Louis,Chief Financial Officer,Officer,2023.0
4,5238,https://my.bursamalaysia.com/stock-details?sto...,Capt. Suresh Bangah,Director - Flight Operations,Officer,2013.0

In [3]:
df = csv
bad_ids = df[~df["company_id"].str.fullmatch(r"\d{4}")]
print("Bad company_ids:")
print(bad_ids['company_id'])

Bad company_ids:
0       03050
1       03050
1800    03008
1933    03053
1934    03053
1935    03053
1936    03053
1937    03053
1938    03053
1939    03053
1940    03053
1941    03053
1942    03053
1943    03053
1944    03053
1945    03053
1946    03053
1947    03053
1948    03053
1949    03053
1950    03053
1951    03053
2260    03021
2261    03021
3203    03022
3225    03041
3322    03046
Name: company_id, dtype: object

In [4]:
# Ensure company_id is string
csv["company_id"] = csv["company_id"].astype(str)

# Detect bad IDs (not exactly 4 digits)
bad_mask = ~csv["company_id"].str.fullmatch(r"\d{4}")

# Print them
print("Bad company_ids:")
print(csv.loc[bad_mask, "company_id"])

# Fix only the bad ones
csv.loc[bad_mask, "company_id"] = csv.loc[bad_mask, "company_id"].str.zfill(4)

Bad company_ids:
0       03050
1       03050
1800    03008
1933    03053
1934    03053
1935    03053
1936    03053
1937    03053
1938    03053
1939    03053
1940    03053
1941    03053
1942    03053
1943    03053
1944    03053
1945    03053
1946    03053
1947    03053
1948    03053
1949    03053
1950    03053
1951    03053
2260    03021
2261    03021
3203    03022
3225    03041
3322    03046
Name: company_id, dtype: object

In [5]:
# Ensure company_id is string type
csv["company_id"] = csv["company_id"].astype(str)

# Find malformed IDs that are not 4-digit strings
bad_ids = csv[~csv["company_id"].str.fullmatch(r"\d{4}")]

# Report bad IDs
print("Bad company_ids:")
print(bad_ids["company_id"])

Bad company_ids:
0       03050
1       03050
1800    03008
1933    03053
1934    03053
1935    03053
1936    03053
1937    03053
1938    03053
1939    03053
1940    03053
1941    03053
1942    03053
1943    03053
1944    03053
1945    03053
1946    03053
1947    03053
1948    03053
1949    03053
1950    03053
1951    03053
2260    03021
2261    03021
3203    03022
3225    03041
3322    03046
Name: company_id, dtype: object

In [6]:
csv["company_id"].nunique()

172

In [7]:
df = csv

In [8]:
merged = df

In [9]:
len(merged.columns)

6

In [10]:
merged

,company_id,company_url,Name,Designation,Role,Since
0,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
1,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
2,5238,https://my.bursamalaysia.com/stock-details?sto...,Mr. Benyamin Bin Ismail,Chief Executive Officer,Officer,NaN
3,5238,https://my.bursamalaysia.com/stock-details?sto...,Ms. Lavinia Louis,Chief Financial Officer,Officer,2023.0
4,5238,https://my.bursamalaysia.com/stock-details?sto...,Capt. Suresh Bangah,Director - Flight Operations,Officer,2013.0
...,...,...,...,...,...,...
3465,3905,https://my.bursamalaysia.com/stock-details?sto...,Mr. Hoy Ping Chew,Non-Independent Non-Executive Director,Director,2023.0
3466,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3467,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3468,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3469,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN

In [ ]:
bursa_registration = pd.read_csv("../matched_companies_from_ssm.csv",dtype={"company_id": str,"companyNo": str})
bursa_registration["companyNo"] = (
    bursa_registration["companyNo"]
    .astype(str)
    .str.replace(r"\.0$", "", regex=True)
    .str.strip()
)
bursa_registration.head()

,company_name,name_db,companyNo,oldCompanyNo,company_type
0,7-ELEVEN MALAYSIA HOLDINGS BERHAD,7-ELEVEN MALAYSIA HOLDINGS BERHAD,201301028701.0,1058531-W,Company
1,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,Company
2,A-RANK BERHAD,A-RANK ASSOCIATES SDN. BHD.,199701029773.0,445272-P,Company
3,ABLE GLOBAL BERHAD,ABLE GLOBAL (MM2H) SDN. BHD.,199501013751.0,342952-P,Company
4,ABLEGROUP BERHAD,ABLEGROUP BERHAD,200401015685.0,654188-H,Company

In [12]:
company_id = pd.read_csv("../../../list_bursa_ids/bursa_company_list.csv", dtype={"company_id": str})
company_id["company_id"] = company_id["company_id"].str.strip().str.zfill(4)

In [13]:
merge = pd.merge(bursa_registration,company_id,on="company_name",how="inner")
merge

,company_name,name_db,companyNo,oldCompanyNo,company_type,company_id
0,7-ELEVEN MALAYSIA HOLDINGS BERHAD,7-ELEVEN MALAYSIA HOLDINGS BERHAD,201301028701.0,1058531-W,Company,5250
1,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,Company,5326
2,A-RANK BERHAD,A-RANK ASSOCIATES SDN. BHD.,199701029773.0,445272-P,Company,7214
3,ABLE GLOBAL BERHAD,ABLE GLOBAL (MM2H) SDN. BHD.,199501013751.0,342952-P,Company,7167
4,ABLEGROUP BERHAD,ABLEGROUP BERHAD,200401015685.0,654188-H,Company,7086
...,...,...,...,...,...,...
1073,TOTAL DYNAMIC HOLDINGS BERHAD,TOTAL DYNAMIC HOLDINGS BERHAD,202201036425.0,1482122-A,Company,03058
1074,TP TEC HOLDING BERHAD,TP TEC HOLDING BERHAD,202401020280.0,1566129-V,Company,03061
1075,TSIC BERHAD,TSIC BERHAD,202301036647.0,1530570-U,Company,03062
1076,UCI RESOURCES BERHAD,UCI RESOURCES BERHAD,202001015323.0,1371643-X,Company,03043
1077,UNI WALL APS HOLDINGS BERHAD,UNI WALL APS HOLDINGS BERHAD,201801007506.0,1269520-X,Company,03017

In [14]:
len(merge["company_id"].drop_duplicates())

1078

In [15]:
merge_copy = merge.copy()

In [16]:
merge = merge.drop(columns="company_type")
merge = merge.rename(columns={
    "company_name": "company_name_bursa",
    "name_db": "company_name_api",
    "companyNo": "registration_number",
    "oldCompanyNo": "old_registration_number"
})
# merge.to_csv("bursa_company_registra.csv", index=False)

In [17]:
merge

,company_name_bursa,company_name_api,registration_number,old_registration_number,company_id
0,7-ELEVEN MALAYSIA HOLDINGS BERHAD,7-ELEVEN MALAYSIA HOLDINGS BERHAD,201301028701.0,1058531-W,5250
1,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326
2,A-RANK BERHAD,A-RANK ASSOCIATES SDN. BHD.,199701029773.0,445272-P,7214
3,ABLE GLOBAL BERHAD,ABLE GLOBAL (MM2H) SDN. BHD.,199501013751.0,342952-P,7167
4,ABLEGROUP BERHAD,ABLEGROUP BERHAD,200401015685.0,654188-H,7086
...,...,...,...,...,...
1073,TOTAL DYNAMIC HOLDINGS BERHAD,TOTAL DYNAMIC HOLDINGS BERHAD,202201036425.0,1482122-A,03058
1074,TP TEC HOLDING BERHAD,TP TEC HOLDING BERHAD,202401020280.0,1566129-V,03061
1075,TSIC BERHAD,TSIC BERHAD,202301036647.0,1530570-U,03062
1076,UCI RESOURCES BERHAD,UCI RESOURCES BERHAD,202001015323.0,1371643-X,03043
1077,UNI WALL APS HOLDINGS BERHAD,UNI WALL APS HOLDINGS BERHAD,201801007506.0,1269520-X,03017

In [18]:
merged

,company_id,company_url,Name,Designation,Role,Since
0,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
1,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
2,5238,https://my.bursamalaysia.com/stock-details?sto...,Mr. Benyamin Bin Ismail,Chief Executive Officer,Officer,NaN
3,5238,https://my.bursamalaysia.com/stock-details?sto...,Ms. Lavinia Louis,Chief Financial Officer,Officer,2023.0
4,5238,https://my.bursamalaysia.com/stock-details?sto...,Capt. Suresh Bangah,Director - Flight Operations,Officer,2013.0
...,...,...,...,...,...,...
3465,3905,https://my.bursamalaysia.com/stock-details?sto...,Mr. Hoy Ping Chew,Non-Independent Non-Executive Director,Director,2023.0
3466,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3467,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3468,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3469,3905,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN

In [19]:
merged["company_id"].nunique()

172

In [20]:
merge["company_id"] = merge["company_id"].str.strip()
merged["company_id"] = merged["company_id"].str.strip()

In [21]:
merge["company_id"] = merge["company_id"].astype(str)
merged["company_id"] = merged["company_id"].astype(str)
final_merge = merge.merge(merged, on="company_id", how="inner")

In [22]:
final_merge['company_id'].nunique()

172

In [23]:
merge

,company_name_bursa,company_name_api,registration_number,old_registration_number,company_id
0,7-ELEVEN MALAYSIA HOLDINGS BERHAD,7-ELEVEN MALAYSIA HOLDINGS BERHAD,201301028701.0,1058531-W,5250
1,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326
2,A-RANK BERHAD,A-RANK ASSOCIATES SDN. BHD.,199701029773.0,445272-P,7214
3,ABLE GLOBAL BERHAD,ABLE GLOBAL (MM2H) SDN. BHD.,199501013751.0,342952-P,7167
4,ABLEGROUP BERHAD,ABLEGROUP BERHAD,200401015685.0,654188-H,7086
...,...,...,...,...,...
1073,TOTAL DYNAMIC HOLDINGS BERHAD,TOTAL DYNAMIC HOLDINGS BERHAD,202201036425.0,1482122-A,03058
1074,TP TEC HOLDING BERHAD,TP TEC HOLDING BERHAD,202401020280.0,1566129-V,03061
1075,TSIC BERHAD,TSIC BERHAD,202301036647.0,1530570-U,03062
1076,UCI RESOURCES BERHAD,UCI RESOURCES BERHAD,202001015323.0,1371643-X,03043
1077,UNI WALL APS HOLDINGS BERHAD,UNI WALL APS HOLDINGS BERHAD,201801007506.0,1269520-X,03017

In [24]:
(final_merge.isnull().mean() * 100).sort_values(ascending=False).to_frame("missing_%").style.background_gradient(cmap='Reds')

In [25]:
df=final_merge

In [26]:
df

,company_name_bursa,company_name_api,registration_number,old_registration_number,company_id,company_url,Name,Designation,Role,Since
0,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Thiam Wah Lee,"Chief Executive Officer, Executive Director",Both,2023.0
1,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Ms. Yee Peng Ong,Chief Financial Officer,Officer,NaN
2,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Eng Kwang Yong,Chief Operating Officer,Officer,NaN
3,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Ms. Sau Chan Leong,Director - Business Development,Officer,NaN
4,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Yong Cherng Chia,Director - Logistics,Officer,NaN
...,...,...,...,...,...,...,...,...,...,...
3465,MCOM HOLDINGS BERHAD,MCOM HOLDINGS BERHAD,201701034106.0,1248277-X,03022,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3466,ONETECH SOLUTIONS HOLDINGS BERHAD,ONETECH SOLUTIONS HOLDINGS BERHAD,201901002105.0,1311431-K,03041,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3467,SL INNOVATION CAPITAL BERHAD,SL INNOVATION CAPITAL BERHAD,201101044035.0,972155-K,03008,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3468,SUNMOW HOLDING BERHAD,SUNMOW HOLDING BERHAD,202001024626.0,1380946-V,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3469,SUNMOW HOLDING BERHAD,SUNMOW HOLDING BERHAD,202001024626.0,1380946-V,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN

In [27]:
# ── Your DataFrame ──
df = df.copy()
df.columns = df.columns.str.replace("-", " ").str.strip().str.strip().str.lower().str.replace(" ", "_").str.replace("-", "_")
df

,company_name_bursa,company_name_api,registration_number,old_registration_number,company_id,company_url,name,designation,role,since
0,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Thiam Wah Lee,"Chief Executive Officer, Executive Director",Both,2023.0
1,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Ms. Yee Peng Ong,Chief Financial Officer,Officer,NaN
2,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Eng Kwang Yong,Chief Operating Officer,Officer,NaN
3,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Ms. Sau Chan Leong,Director - Business Development,Officer,NaN
4,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Yong Cherng Chia,Director - Logistics,Officer,NaN
...,...,...,...,...,...,...,...,...,...,...
3465,MCOM HOLDINGS BERHAD,MCOM HOLDINGS BERHAD,201701034106.0,1248277-X,03022,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3466,ONETECH SOLUTIONS HOLDINGS BERHAD,ONETECH SOLUTIONS HOLDINGS BERHAD,201901002105.0,1311431-K,03041,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3467,SL INNOVATION CAPITAL BERHAD,SL INNOVATION CAPITAL BERHAD,201101044035.0,972155-K,03008,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3468,SUNMOW HOLDING BERHAD,SUNMOW HOLDING BERHAD,202001024626.0,1380946-V,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3469,SUNMOW HOLDING BERHAD,SUNMOW HOLDING BERHAD,202001024626.0,1380946-V,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN

In [28]:
df.columns

Index(['company_name_bursa', 'company_name_api', 'registration_number',
       'old_registration_number', 'company_id', 'company_url', 'name',
       'designation', 'role', 'since'],
      dtype='object')

In [29]:
import re
df.columns = (
    df.columns
    .str.replace("-", " ", regex=False)        # Replace hyphens with spaces
    .str.replace("/", " ", regex=False) 
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)   # Remove non-word characters like . , &
    .str.replace(r"\s+", "_", regex=True)      # Convert spaces to single underscore
    .str.replace(r"_+", "_", regex=True)       # Collapse multiple underscores to one
)

In [30]:
df

,company_name_bursa,company_name_api,registration_number,old_registration_number,company_id,company_url,name,designation,role,since
0,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Thiam Wah Lee,"Chief Executive Officer, Executive Director",Both,2023.0
1,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Ms. Yee Peng Ong,Chief Financial Officer,Officer,NaN
2,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Eng Kwang Yong,Chief Operating Officer,Officer,NaN
3,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Ms. Sau Chan Leong,Director - Business Development,Officer,NaN
4,99 SPEED MART RETAIL HOLDINGS BERHAD,99 SPEED MART RETAIL HOLDINGS BERHAD,202301017784.0,1511706-T,5326,https://my.bursamalaysia.com/stock-details?sto...,Mr. Yong Cherng Chia,Director - Logistics,Officer,NaN
...,...,...,...,...,...,...,...,...,...,...
3465,MCOM HOLDINGS BERHAD,MCOM HOLDINGS BERHAD,201701034106.0,1248277-X,03022,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3466,ONETECH SOLUTIONS HOLDINGS BERHAD,ONETECH SOLUTIONS HOLDINGS BERHAD,201901002105.0,1311431-K,03041,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3467,SL INNOVATION CAPITAL BERHAD,SL INNOVATION CAPITAL BERHAD,201101044035.0,972155-K,03008,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3468,SUNMOW HOLDING BERHAD,SUNMOW HOLDING BERHAD,202001024626.0,1380946-V,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN
3469,SUNMOW HOLDING BERHAD,SUNMOW HOLDING BERHAD,202001024626.0,1380946-V,03050,https://my.bursamalaysia.com/stock-details?sto...,NaN,NaN,NaN,NaN

In [31]:
df.columns.tolist()

['company_name_bursa',
 'company_name_api',
 'registration_number',
 'old_registration_number',
 'company_id',
 'company_url',
 'name',
 'designation',
 'role',
 'since']

In [32]:
# Check for duplicate column names
duplicates = df.columns[df.columns.duplicated()]
print("Duplicate columns:", duplicates.tolist())
df = df.loc[:, ~df.columns.duplicated()]

Duplicate columns: []

In [33]:
# Get null ratios sorted
null_ratios = df.isnull().mean().sort_values(ascending=False)

# Convert to DataFrame with formatted percentage
summary_df = pd.DataFrame({
    "column": null_ratios.index,
    "null_ratio": (null_ratios * 100).map("{:.2f}%".format)
})

# Save to CSV
# summary_df.to_csv("/insider_null_ratio_summary.csv", index=False)
summary_df.head()

                            column null_ratio
since                        since     55.53%
name                          name     45.50%
designation            designation     45.50%
role                          role     45.50%
company_name_api  company_name_api      2.10%

In [34]:
len(df["registration_number"].drop_duplicates())

170

In [35]:
df = df.dropna(subset=["registration_number"])

In [36]:
df['registration_number'].nunique()

169

In [37]:
from sqlalchemy import create_engine
import pandas as pd
from dotenv import load_dotenv
import os

# ── Load environment variables ──
load_dotenv()

# ── Read DB credentials ──
user = os.getenv("PG_USER")
password = os.getenv("PG_PASSWORD")
host = os.getenv("PG_HOST")
port = os.getenv("PG_PORT")
database = os.getenv("PG_DATABASE")

# ── Create connection string ──
connection_url = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(connection_url)

# ── Your DataFrame ──
df = df.copy()

# ── Push to DB ──
df.to_sql("public_complete_directors_executives", engine, schema="public", index=False, if_exists="replace")

print("✅ Uploaded to 'public_complete_directors_executives' with normalized column names.")

✅ Uploaded to 'public_complete_directors_executives' with normalized column names.